name: publish
on:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up latest Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Upgrade to latest setuptools and wheel
      run: pip install --user --upgrade setuptools wheel
    - name: Build a binary wheel and a source tarball to dist/
      run: python setup.py sdist bdist_wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: '__token__'
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: See CHANGELOG.rst
        draft: false
        prerelease: false
    - name: Upload dist/ as workflow artifact (mostly for debugging)
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
